version: '3.8'

services:
  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: whatsapp-flow-rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - whatsapp-flow-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: whatsapp-flow-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=WhatsappFlowDb
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - whatsapp-flow-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  # API Gateway
  api-gateway:
    build:
      context: ./Gateways/ApiGateway
      dockerfile: Dockerfile
    container_name: whatsapp-flow-api-gateway
    ports:
      - "5000:80"
    depends_on:
      - identity-service
      - flow-service
      - webhook-service
    networks:
      - whatsapp-flow-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  # Identity Service
  identity-service:
    build:
      context: ./Services/IdentityService
      dockerfile: Dockerfile
    container_name: whatsapp-flow-identity-service
    ports:
      - "5001:80"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - whatsapp-flow-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://root:example@mongodb:27017/?authSource=admin
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123

  # Flow Service
  flow-service:
    build:
      context: ./Services/FlowService
      dockerfile: Dockerfile
    container_name: whatsapp-flow-service
    ports:
      - "5002:80"
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - whatsapp-flow-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://root:example@mongodb:27017/?authSource=admin
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123

  # Webhook Service
  webhook-service:
    build:
      context: ./Services/WebhookService
      dockerfile: Dockerfile
    container_name: whatsapp-flow-webhook-service
    ports:
      - "5003:80"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - whatsapp-flow-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=admin
      - RabbitMQ__Password=admin123

volumes:
  rabbitmq_data:
  mongodb_data:

networks:
  whatsapp-flow-network:
    driver: bridge 